version: '3.8'

services:
  airflow_db:
    image: postgres:15
    container_name: airflow_db
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - airflow_db_data:/var/lib/postgresql/data

  airflow_app:
    build: .
    container_name: airflow_app
    # --- AJUSTE DE PERMISSÃO ---
    user: "0:0" 
    environment:
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow_db:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__TEST_CONNECTION=Enabled
      # --- AJUSTE DE ESTABILIDADE ---
      - AIRFLOW__CORE__UNIT_TEST_MODE=True
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      
      # --- AUTOMATED CONNECTIONS ---
      - AIRFLOW_CONN_SUPABASE_CONN=postgresql://${SUPABASE_USER}:${SUPABASE_PASSWORD}@${SUPABASE_HOST}:${SUPABASE_PORT}/${SUPABASE_DB}
      - SUPABASE_HOST=${SUPABASE_HOST}
      - SUPABASE_USER=${SUPABASE_USER}
      - SUPABASE_PASSWORD=${SUPABASE_PASSWORD}
      - SUPABASE_DB=${SUPABASE_DB}
      - SUPABASE_PORT=${SUPABASE_PORT}

      # Configuração de E-mail
      - AIRFLOW__SMTP__SMTP_HOST=${AIRFLOW__SMTP__SMTP_HOST:-smtp.gmail.com}
      - AIRFLOW__SMTP__SMTP_STARTTLS=${AIRFLOW__SMTP__SMTP_STARTTLS:-True}
      - AIRFLOW__SMTP__SMTP_SSL=${AIRFLOW__SMTP__SMTP_SSL:-False}
      - AIRFLOW__SMTP__SMTP_USER=${AIRFLOW__SMTP__SMTP_USER}
      - AIRFLOW__SMTP__SMTP_PASSWORD=${AIRFLOW__SMTP__SMTP_PASSWORD}
      - AIRFLOW__SMTP__SMTP_PORT=${AIRFLOW__SMTP__SMTP_PORT:-587}
      - AIRFLOW__SMTP__SMTP_MAIL_FROM=${AIRFLOW__SMTP__SMTP_MAIL_FROM}

    ports:
      - "8080:8080"
    volumes:
      - .:/opt/airflow
      - ./tests:/opt/airflow/tests 
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    depends_on:
      airflow_db:
        condition: service_healthy
    # --- AJUSTE NO COMMAND ---
    # Adicionado 'chmod' para garantir que a pasta data seja gravável antes de iniciar
    command: >
      bash -c "chmod -R 777 /opt/airflow/data && 
               airflow db init && 
               airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin && 
               airflow standalone"

volumes:
  airflow_db_data: