version: '3.8'

services:
  airflow_db:
    image: postgres:15
    container_name: airflow_db
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - airflow_db_data:/var/lib/postgresql/data

  airflow_app:
    image: apache/airflow:2.7.1
    container_name: airflow_app
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow_db:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__TEST_CONNECTION=Enabled
      
      # Vari√°veis lidas do .env
      - SUPABASE_HOST=${SUPABASE_HOST}
      - SUPABASE_USER=${SUPABASE_USER}
      - SUPABASE_PASSWORD=${SUPABASE_PASSWORD}
      - SUPABASE_DB=${SUPABASE_DB}
      - SUPABASE_PORT=${SUPABASE_PORT}
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dbt:/opt/airflow/dbt
      - ./plugins:/opt/airflow/plugins
    depends_on:
      airflow_db:
        condition: service_healthy
    command: standalone

volumes:
  airflow_db_data: