version: '3.8'
services:
  # --- BANCO DE DADOS (Onde os dados ser√£o armazenados) ---
  postgres:
    image: postgres:15
    container_name: postgres_dw
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=analytics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- AIRFLOW (O maestro que orquestra os scripts) ---
  airflow:
    image: apache/airflow:2.7.1-python3.9
    container_name: airflow_app
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/analytics
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dbt_project:/opt/airflow/dbt_project
    ports:
      - "8080:8080"
    command: standalone
    depends_on:
      - postgres

volumes:
  postgres_data: